### ISSUE TITLE
Client: Try all IP addresses of a host when connecting

### ISSUE THREAD

**Issue by mkauf** [c-icap/c-icap-server#11]
Currently c-icap tries to connect to the first IP address that is returned by ``getaddrinfo()``. Sometimes this does not work, and it would work with the second, third, ... IP address that is returned by ``getaddrinfo()``.

Clients should try to connect to every IP address of a host in a loop and use the first connection that can be established successfully. This is important for clients that have only an IPv4 or only an IPv6 address, or whose routing does only work for IPv4 or only for IPv6.

There is example source code available, e.g. page 30 of http://www.6deploy.eu/tutorials/210-6deploy_devel_v0_4.pdf

**Comment by chtsanti** [comment]
### Comments about this issue.

There is a serious problem with the ci_connect_to_nonblock function: The getaddrinfo is a blocking function and used with the ci_connect_to_nonblock which supposed that it is nonblocking.

Yes the problem is known, however as is now the ci_connect_to_nonblock, it is  valid only if it used with IP addresses (so there is one IP address). The getaddrinfo here is mostly used to convert IP addresses to struct addrinfo.

Alternate fixes/implementations:

1) Fix the `ci_connect_to_nonblock` to accepts only IP addresses. The `ci_connect_to` is a blocking function, and a correct implementation should use the `getaddrinfo` inside `ci_connect_to` and  call the `ci_connect_to_nonblock` for each IP address. Maybe implement new `ci_connector_*`  family functions.

2) Fix the `ci_connect_to_nonblock` to use a nonblocking implementation of getaddrinfo. The connection->fd initially (while the DNS lookup) can be set to a pipe fd or to an eventFD to allow the ci_connection_t object to be used within a select/poll/epoll loop and after ip addresses are received start trying real socket connections.
The major issues with this implementation are 1st) that the ci_connection_t::fd member will change many times its value, while trying to connect to a remote server and 2nd) requires new members to ci_connection_t object.

**Comment by chtsanti** [comment]
Finally I selected to deprecate the existing ci_connect_to_nonblock and ci_connect_to functions and implement new ones.
The new functions works with raw IP addresses, they do not use DNS names.
 The fixes exists only for master branch. 
New functions:
 - ci_host_get_addresses: retrieves the list of ip addresses (IPv6 or IPv4) for
    the given server name.
 - ci_connect_to_address: accepts a ci_sockaddr_t as destination address to connect
 - ci_connect_ms_to_address: same as above but accepts timeout in milliseconds
 - ci_connect_to_address_nonblock: similar to the ci_connect_to_nonblock but 
   uses a ci_sockaddr_t as destination address
 - ci_wait_ms_for_data: similar to the existing ci_wait_for_data but accepts timeout
    in miliseconds
 - ci_tls_connect_to_address_nonblock: Similar to old ci_tls_connect_nonblock
    method but accepts an ip address as destination and also the server name
    to use as SNI info and when verifying remote end.
  - ci_tls_connect_to_address: similar to old ci_tls_connect but accepts
    an ip address as destination and also the server name to use.
  - ci_tls_connect_ms_to_address: similar to the new ci_tls_connect_to_address
    but accepts a timeout value in milliseconds.
  - ci_connection_wait_ms_tls. Similar to existing ci_connection_wait_tls
     but accepts timeout in milliseconds

Other changes:
 - The ci_connect_to_nonblock fixed to accepts only ip addresses (in string form) as destination

Please check commit 114032c56 for example code which uses the new functions.

Tests and comments about are welcome.

**Comment by mkauf** [comment]
Thank you for the implementation! This looks very promising.

I hope that I can review the code with a teammate, but this will take some time.

When do you plan to use the current "master" branch for an official release?

**Comment by chtsanti** [comment]
> When do you plan to use the current "master" branch for an official release?

After the followings are finished:
 -  Some changes in statistics interface, to support gcc atomic operations (and maybe C11 atomic operations), and provide 1-2 API functions for more control over statistics and some shared (among c-icap kids processes) variables.
 - Document and hopefully freeze netio related API
 - Change some "#define" macros to be inlinned functions, mostly these which are defined in netio.h and arrays.h

**Comment by mkauf** [comment]
To test your commits, a teammate has used the current "master" branch of c-icap and integrated it in our software. After adjusting our code to the changed API of c-icap, everything worked as expected :) Thanks a lot for this improvement.

We have also checked the new code with Valgrind and found that the variable "cfg_params_allocator" is never freed. Maybe a new function ci_cfg_lib_uninit() (or similar) could be created to free this variable. This would make Valgrind easier to use with c-icap.
