### ISSUE TITLE
Replace Berkley DB with other implementation

### ISSUE THREAD

**Issue by frankcrawford** [c-icap/c-icap-server#43]
Since Berkley DB has moved to a more restrictive license, many Linux distributions are dropping it.

Is it possible to use a different DB implementation in place of it, or is it possible to look at implementing something different in the future?

This has come up as an issue with adding c-icap to Fedora, as BDB is now deprecated, and currently will need a special older bundled version.  Eventually even that version should go away.

**Comment by frankcrawford** [comment]
Here is a list of some alternates: https://fedoraproject.org/wiki/User:Pkubat/BerkeleyDB_alternatives

**Comment by chtsanti** [comment]
Lookup-tables based on lmdb and tdb can be easily implemented  in c-icap.
The lmdb can be used as bdb replacement for c-icap-modules/url_check/SquidGuard databases.
The Tokyo Cabinet is GPL lisensed, a module which implements lookup-tables can be implemented in c-icap-modules package.

The first goal is to use lmdb instead of bdb.

**Comment by frankcrawford** [comment]
Out of interest, has there been any update on this plan?

**Comment by chtsanti** [comment]
Yes there is a small project which uses lmdb databases for both  c-icap and c-icap-modules.
Also there is a second small project to implement Tokyo Cabinet based modules as part of the  c-icap-modules package.
The two projects are in final stages only some cleanup required before published and merged to master branches.

**Comment by frankcrawford** [comment]
@chtsanti thanks for that update, that is good to hear.

Once they are ready, I'm willing to test them out, although mine is not a bit installation, just my home network.

**Comment by bkmgit** [comment]
Would a module with [TKRZW](https://dbmx.net/tkrzw/) also be considered?

**Comment by chtsanti** [comment]
Support for lmdb lookup tables exists in latest c-icap master branch.
Also in latest c-icap-modules the url_check service can use, and by default uses, lmdb to implement  squidguard like databases.

**Comment by frankcrawford** [comment]
Thanks for that, we will look at it.

**Comment by chtsanti** [comment]
In c-icap-modules master branch also exist an implementation for TokyoCabinet based lookup tables for use with c-icap server.

> Would a module with [TKRZW](https://dbmx.net/tkrzw/) also be considered?

The TKRZW can not be used as is with c-icap because a TKRZW databasecan not be used by more than one processes. But someone can use the TKRZW-RPC.

I will close this issue, there are alternates to BerkeleyDB  now and will be available to the c-icap-0.6.x and c-icap-modules-0.6.x releases.
